import {
  PlayerCard,
  TimeInputsCard,
  MeasureTraversalCard,
  LoopListCard,
  SongSettings,
} from './components'

export function DesktopLayout({
  mediaPlayerRef,
  isLoading,
  currentTime,
  duration,
  loopStart,
  loopEnd,
  playbackRate,
  isPlaying,
  isScrubbing,
  scrubTime,
  controlsDisabled,
  playerMetadata,
  measures,
  collapsedLoops,
  setCollapsedLoops,
  eqGains,
  eqPreset,
  type,
  showSettings,
  onToggleSettings,
  onIntervalChange,
  onSeek,
  onScrubStart,
  onScrubEnd,
  onPlay,
  onPause,
  onRestartPlayer,
  onRestartLoop,
  onMarkLoopStart,
  onMarkLoopEnd,
  onSaveLoop,
  onPlaybackRateChange,
  onLoopStartChange,
  onLoopEndChange,
  onCurrentTimeChange,
  onMeasuresChange,
  onLoadLoop,
  onDeleteLoop,
  onTitleChange,
  onBpmChange,
  onBeatsPerMeasureChange,
  onEqBandChange,
  onEqPresetChange,
}) {
  return (
    <div className='h-full w-full px-2 pb-6 overflow-y-auto grid lg:grid-cols-[2fr_1fr] lg:overflow-hidden'>
      <section className='md:p-2'>
        <PlayerCard
          mediaPlayerRef={mediaPlayerRef}
          isLoading={isLoading}
          currentTime={currentTime}
          duration={duration}
          loopStart={loopStart}
          loopEnd={loopEnd}
          playbackRate={playbackRate}
          isPlaying={isPlaying}
          isScrubbing={isScrubbing}
          scrubTime={scrubTime}
          controlsDisabled={controlsDisabled}
          onIntervalChange={onIntervalChange}
          onSeek={onSeek}
          onScrubStart={onScrubStart}
          onScrubEnd={onScrubEnd}
          onPlay={onPlay}
          onPause={onPause}
          onRestartPlayer={onRestartPlayer}
          onRestartLoop={onRestartLoop}
          onMarkLoopStart={onMarkLoopStart}
          onMarkLoopEnd={onMarkLoopEnd}
          onSaveLoop={onSaveLoop}
          onPlaybackRateChange={onPlaybackRateChange}
        />
      </section>

      <section className='pt-6 pb-6 md:p-2 flex flex-col gap-2 lg:overflow-y-auto'>
        {showSettings ? (
          <SongSettings
            onClose={onToggleSettings}
            type={type}
            bpm={playerMetadata.bpm}
            beatsPerMeasure={playerMetadata.beatsPerMeasure}
            onBpmChange={onBpmChange}
            onBeatsPerMeasureChange={onBeatsPerMeasureChange}
            gains={eqGains}
            onBandChange={onEqBandChange}
            activePreset={eqPreset}
            onPresetChange={onEqPresetChange}
            playerRef={mediaPlayerRef}
          />
        ) : (
          <>
            <TimeInputsCard
              loopStart={loopStart}
              loopEnd={loopEnd}
              currentTime={currentTime}
              duration={duration}
              controlsDisabled={controlsDisabled}
              onLoopStartChange={onLoopStartChange}
              onLoopEndChange={onLoopEndChange}
              onCurrentTimeChange={onCurrentTimeChange}
            />
            <MeasureTraversalCard
              bpm={playerMetadata.bpm}
              beatsPerMeasure={playerMetadata.beatsPerMeasure}
              measures={measures}
              loopStart={loopStart}
              loopEnd={loopEnd}
              onLoopStartChange={onLoopStartChange}
              onLoopEndChange={onLoopEndChange}
              onSeek={onSeek}
              onMeasuresChange={onMeasuresChange}
            />
            <LoopListCard
              loops={playerMetadata.loops}
              loopStart={loopStart}
              loopEnd={loopEnd}
              collapsedLoops={collapsedLoops}
              setCollapsedLoops={setCollapsedLoops}
              onLoadLoop={onLoadLoop}
              onDeleteLoop={onDeleteLoop}
              onTitleChange={onTitleChange}
            />
          </>
        )}
      </section>
    </div>
  )
}
