name: Android CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # build node files/capacitor
      - name: set up NodeJS
        uses: actions/setup-node@v4.0.3
      - name: build env
        env:
          CI: ''
        run: |
          chmod +x android-build-debug.sh
          ./android-build-debug.sh

      #JDK
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 20
          distribution: temurin
          cache: gradle

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.1
        
      # Invalidate the Gradle cache
      - name: Clear Gradle Cache
        run: rm -rf $HOME/.gradle/caches/
        
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
      - name: Build with Gradle
        run: |
          cd android
          ./gradlew assembleDebug --debug
